apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: photoprism-manifests
spec:
  dependsOn:
    - name: mariadb-operator
    - name: gateway-api
      namespace: flux-system
  kubeConfig:
    secretRef:
      name: vc-vcluster-b
      key: config
  targetNamespace: default
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./tenant/tenant-b/photoprism/manifests
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: photoprism-helm
spec:
  dependsOn:
    - name: photoprism-manifests
  targetNamespace: vcluster-b
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./tenant/tenant-b/photoprism/helm
  prune: true
  timeout: 5m