apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  database: photoprism
  username: photoprism
  passwordSecretKeyRef:
    name: mariadb
    key: password
  connection:
    secretName: photoprism
    secretTemplate:
      key: dsn
    params:
      parseTime: "true"

  image:
    repository: mariadb
    tag: "11.0.2"
    pullPolicy: IfNotPresent

  port: 3306

  volumeClaimTemplate:
    metadata:
      annotations:
        vcluster.loft.sh/skip-translate: "true"
    # TODO:
    # vcluster does not sync PVCs if storageClassname is empty, therefore Kubernetes can't set the default one. Raise a PR upstream. See:
    # https://github.com/loft-sh/vcluster/blob/main/pkg/controllers/resources/persistentvolumeclaims/translate.go#L55
    # https://kubernetes.io/docs/concepts/storage/storage-classes/#default-storageclass
    storageClassName: standard
    resources:
      requests:
        storage: 100Mi
    accessModes:
      - ReadWriteOnce

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

  metrics:
    exporter:
      image:
        repository: prom/mysqld-exporter
        tag: "v0.14.0"
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 300m
          memory: 512Mi
    serviceMonitor:
      prometheusRelease: kube-prometheus-stack
      interval: 10s
      scrapeTimeout: 10s
