apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: photoprism
spec:
  parentRefs:
    - name: traefik
      namespace: traefik
  hostnames:
    - "tenant-b.traefik.local"
  rules:
    - backendRefs:
        - kind: Service
          name: photoprism
          port: 80
