apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: "23.1.0"
  interval: 5m
  values:
    logs:
      general:
        level: INFO
      access:
        enabled: true
    ingressRoute:
      dashboard:
        enabled: false
    ingressClass:
      enabled: true
      isDefaultClass: true
    ports:
      web:
        redirectTo: websecure
    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik
      kubernetesIngress:
        enabled: true
        ingressClass: traefik
    additionalArguments:
      - "--serverstransport.insecureskipverify"
      - "--experimental.kubernetesgateway"
      - "--providers.kubernetesgateway"
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 172.18.0.200
    deployment:
      enabled: true