apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
spec:
  kubeConfig:
    secretRef:
      name: vc-vcluster-b
      key: config
  releaseName: photoprism
  targetNamespace: default
  storageNamespace: default
  chart:
    spec:
      chart: photoprism
      sourceRef:
        kind: HelmRepository
        name: mmontes
      version: "0.4.0"
  interval: 5m
  values:
    image:
      repository: photoprism/photoprism
      tag: "221118-jammy"
      pullPolicy: IfNotPresent
    env:
      PHOTOPRISM_AUTH_MODE: public
      PHOTOPRISM_PUBLIC: true
      PHOTOPRISM_READONLY: false
      PHOTOPRISM_LOG_LEVEL: debug
    secretRef: null
    persistence:
      enabled: true
      volumes:
        - name: originals
          persistentVolumeClaim:
            claimName: photoprism-originals
        - name: import
          persistentVolumeClaim:
            claimName: photoprism-import
        - name: storage
          persistentVolumeClaim:
            claimName: photoprism-storage
      volumeMounts:
        - name: originals
          mountPath: /photoprism/originals
        - name: import
          mountPath: /photoprism/import
        - name: storage
          mountPath: /photoprism/storage
    database:
      driver: mysql
      dsnSecretKeyRef:
        name: photoprism
        key: dsn
    sync:
      enabled: true
      cron: "* */1 * * *"
      resources:
        requests:
          memory: 300Mi
        limits:
          memory: 1Gi
    service:
      type: ClusterIP
      port: 80
    resources:
      requests:
        memory: 300Mi
      limits:
        memory: 1Gi