apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vcluster-b
spec:
  chart:
    spec:
      chart: vcluster
      sourceRef:
        kind: HelmRepository
        name: loft
      version: "0.15.2"
  interval: 5m
  values:
    service:
      type: LoadBalancer
    syncer:
      serviceAnnotations:
        metallb.universe.tf/loadBalancerIPs: 172.18.0.211
      extraArgs:
      - --tls-san=172.18.0.211
      - --out-kube-config-server=https://172.18.0.211
    sync:
      generic:
        clusterRole:
          extraRules:
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions
              verbs:
                - get
                - list
                - watch
        role:
          extraRules:
            - apiGroups:
                - gateway.networking.k8s.io  
              resources:
                - httproutes 
              verbs:
                - create
                - delete
                - patch
                - update
                - get
                - list
                - watch
        config: |-
          version: v1beta1
          export:
            - apiVersion: gateway.networking.k8s.io/v1beta1
              kind: HTTPRoute 
              patches:
                - op: rewriteName
                  path: .spec.rules[*].backendRefs[*].name
                - apiVersion: monitoring.coreos.com/v1
                  kind: ServiceMonitor
                  patches:
                    - op: add
                      path: .metadata.labels
                      value:
                        release: kube-prometheus-stack
                    - op: copyFromObject
                      fromPath: .metadata.labels['release'] 
                      path: .metadata.labels['release']
                    - op: replace
                      path: .spec.namespaceSelector
                      value:
                        any: false
                        matchNames: []
                    - op: rewriteName
                      path: .spec.endpoints[*]
                    - op: rewriteLabelKey
                      path: .spec.jobLabel
                    - op: rewriteLabelKey
                      path: .spec.targetLabels[*]
                    - op: rewriteLabelKey
                      path: .spec.podTargetLabels[*]
                    - op: rewriteLabelExpressionsSelector
                      path: .spec.selector