apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vcluster-b
spec:
  chart:
    spec:
      chart: vcluster
      sourceRef:
        kind: HelmRepository
        name: loft
      version: "0.15.2"
  interval: 5m
  values:
    service:
      type: LoadBalancer
    syncer:
      serviceAnnotations:
        metallb.universe.tf/loadBalancerIPs: 172.18.0.211
      extraArgs:
      - --tls-san=172.18.0.211
      - --out-kube-config-server=https://172.18.0.211
    multiNamespaceMode:
      enabled: true
    sync:
      generic:
        clusterRole:
          extraRules:
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions
              verbs:
                - get
                - list
                - watch
        role:
          extraRules:
            - apiGroups:
                - gateway.networking.k8s.io  
              resources:
                - httproutes 
              verbs:
                - create
                - delete
                - patch
                - update
                - get
                - list
                - watch
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors 
              verbs:
                - create
                - delete
                - patch
                - update
                - get
                - list
                - watch
            - apiGroups:
                - cert-manager.io
              resources:
                - certificates
              verbs:
                - create
                - delete
                - patch
                - update
                - get
                - list
                - watch
            - apiGroups:
                - source.toolkit.fluxcd.io
                - helm.toolkit.fluxcd.io
              resources:
                - helmreleases
                - helmrepositories
              verbs:
                - create
                - delete
                - patch
                - update
                - get
                - list
                - watch
            - apiGroups:
                - apps
              resources:
                - deployments
              verbs:
                - create
                - delete
                - patch
                - update
                - get
                - list
                - watch
            - apiGroups:
                - ""
              resources:
                - pod
                - service
                - secret
              verbs:
                - create
                - delete
                - patch
                - update
                - get
                - list
                - watch
        config: |-
          version: v1beta1
          export:
            - apiVersion: gateway.networking.k8s.io/v1beta1
              kind: HTTPRoute 
            - apiVersion: monitoring.coreos.com/v1
              kind: ServiceMonitor
              patches:
                - op: add
                  path: .metadata.labels
                  value:
                    release: kube-prometheus-stack
                - op: copyFromObject
                  fromPath: .metadata.labels['release'] 
                  path: .metadata.labels['release']
            - apiVersion: cert-manager.io/v1
              kind: Certificate
            - apiVersion: helm.toolkit.fluxcd.io/v2beta1  
              kind: HelmRelease
            - apiVersion: source.toolkit.fluxcd.io/v1beta2  
              kind: HelmRepository
          import:
            - apiVersion: apps/v1
              kind: Deployment
            - apiVersion: v1
              kind: Pod 
            - apiVersion: v1
              kind: Service
            - apiVersion: v1
              kind: ServiceAccount
            - apiVersion: v1
              kind: Secret
              