apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenant-b
spec:
  dependsOn:
    - name: vcluster-b
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenant/tenant-b
  prune: true