apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenant-a
  namespace: flux-system
spec:
  dependsOn:
    - name: vcluster-a
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenant/tenant-a
  prune: true