apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenant-b
  namespace: vcluster-b
spec:
  dependsOn:
    - name: vcluster-b
      namespace: flux-system
    - name: gateway-api
      namespace: flux-system
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./tenant/tenant-b
  prune: true