apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vcluster-b
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
    - name: metallb-config
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/vcluster-b
  prune: true
  timeout: 5m