apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vcluster-a
spec:
  chart:
    spec:
      chart: vcluster
      sourceRef:
        kind: HelmRepository
        name: loft
      version: "0.15.2"
  interval: 5m
  values:
    syncer:
      extraArgs:
      - --tls-san=127.0.0.1