apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
spec:
  dependsOn:
    - name: gateway-api
      namespace: flux-system
  kubeConfig:
    secretRef:
      name: vc-vcluster-a
      key: config
  targetNamespace: default
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./tenant/tenant-a/nginx
  prune: true
  timeout: 5m