apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-operator
spec:
  chart:
    spec:
      chart: mariadb-operator
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
      version: "0.18.0"
  interval: 5m
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    webhook:
      enabled: true
      certificate:
        certManager: true
      serviceMonitor:
        enabled: true
