apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-operator
spec:
  kubeConfig:
    secretRef:
      name: vc-vcluster-b
      key: config
  releaseName: mariadb-operator
  targetNamespace: default
  storageNamespace: default
  chart:
    spec:
      chart: mariadb-operator
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
      version: "0.18.0"
  install:
    crds: CreateReplace
  interval: 5m
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    webhook:
      enabled: true
      serviceMonitor:
        enabled: true
